apiVersion: v1
kind: Namespace
metadata:
  name: microservices-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  namespace: microservices-demo
  labels:
    app: users
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users-container
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: microservices-demo
spec:
  selector:
    app: users
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
  namespace: microservices-demo
  labels:
    app: orders
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders-container
          image: httpd:alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: microservices-demo
spec:
  selector:
    app: orders
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: microservices-demo
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway-container
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
          env:
            - name: USERS_SERVICE_URL
              value: "http://users-service.microservices-demo.svc.cluster.local"
            - name: ORDERS_SERVICE_URL
              value: "http://orders-service.microservices-demo.svc.cluster.local"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: microservices-demo
spec:
  selector:
    app: gateway
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
